version: '3.4'

services:
  apache.iotdb.samples:
    image: ${DOCKER_REGISTRY-}apacheiotdbsamples
    depends_on:
       iotdb:
        condition: service_healthy
    links:
      - iotdb
    build:
      context: .
      dockerfile: samples/Apache.IoTDB.Samples/Dockerfile
    networks:
        iotdb-network:
          ipv4_address: 172.18.0.2
      
  iotdb:
   image: apache/iotdb:latest
   restart: always
   container_name: iotdb-1
   healthcheck:
      test: ["CMD", "ls", "/iotdb/data"]
      interval: 3s
      timeout: 15s
      retries: 30
      start_period: 30s
   ports:
         - 6667:6667
   networks:
        iotdb-network:
          ipv4_address: 172.18.0.3
   environment:
         - dn_rpc_address=iotdb


networks: 
    iotdb-network:
        external: true
