version: '3.4'

services:
  apache.iotdb.samples:
    image: ${DOCKER_REGISTRY-}apacheiotdbsamples
    depends_on:
       iotdb:
        condition: service_healthy
    links:
      - iotdb
    build:
      context: .
      dockerfile: samples/Apache.IoTDB.Samples/Dockerfile
    networks:
        iotdb-network:
          ipv4_address: 172.18.0.2
      
  iotdb:
   image: apache/iotdb:1.3.2-datanode
   restart: always
   container_name: iotdb-dn-1
   depends_on:
      iotdb-confignode-1:
        condition: service_healthy
   healthcheck:
      test: ["CMD", "ls", "/iotdb/data/datanode/system"]
      interval: 10s
      timeout: 60s
      retries: 30
      start_period: 30s
   ports:
         - 6667:6667
   networks:
        iotdb-network:
          ipv4_address: 172.18.0.3
   environment:
         - dn_rpc_address=iotdb
         - dn_internal_address=iotdb
         - dn_seed_config_node=iotdb-confignode-1:22277
  
  iotdb-confignode-1:
   image: apache/iotdb:1.3.2-confignode
   restart: always
   container_name: iotdb-cn-1
   healthcheck:
      test: ["CMD", "ls", "/iotdb/data"]
      interval: 3s
      timeout: 5s
      retries: 30
      start_period: 30s
   networks:
        iotdb-network:
          ipv4_address: 172.18.0.4
   environment:
         - cn_internal_address=iotdb-confignode-1
         - cn_internal_port=22277
         - cn_seed_config_node=iotdb-confignode-1:22277


networks: 
    iotdb-network:
        external: true
