name: Formatting

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
  merge_group:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dotnet-format:
    runs-on: ubuntu-22.04
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Check formatting
        run: |
          dotnet format --verify-no-changes --verbosity diagnostic
